const datosAlumnos = [
  {
    nombre: "David",
    apellido: "Vargas",
    email: "david.vargas@gmail.com",
    imgPortada: "avatar.jpg",
    web: "https://www.davidvargas.dev",
    tecnologias: [
      "Javascript",
      "HTML",
      "CSS",
      "Bootstrap",
      "Git",
      "VSCode",
      "React",
      "PHP",
      "MySQL",
      "GitHub",
    ],
  },
  {
    nombre: "Juan",
    apellido: "Perez",
    imgPortada: "avatar.jpg",
    email: "juan.perez@gmail.com",
    web: "https://www.juanperez.dev",
    tecnologias: [
      "Javascript",
      "HTML",
      "CSS",
      "Bootstrap",
      "Git",
      "VSCode",
      "React",
      "PHP",
      "MySQL",
      "GitHub",
    ],
  },
  {
    nombre: "Maria",
    apellido: "Perez",
    imgPortada: "avatar.jpg",
    email: "maria.perez@gmail.com",
    web: "https://www.mariaperez.dev",
    tecnologias: [
      "Javascript",
      "HTML",
      "CSS",
      "Bootstrap",
      "Git",
      "VSCode",
      "React",
      "PHP",
      "MySQL",
      "GitHub",
    ],
  },
  {
    nombre: "Carlos",
    apellido: "Perez",
    imgPortada: "avatar.jpg",
    email: "carlos.perez@gmail.com",
    web: "https://www.carlosperez.dev",
    tecnologias: [
      "Javascript",
      "HTML",
      "CSS",
      "Bootstrap",
      "Git",
      "VSCode",
      "React",
      "PHP",
      "MySQL",
      "GitHub",
    ],
  },
];
